services:

 # MongoDB Shell to connect to servers

 client:
  build: 
   context: .
   dockerfile: Dockerfile.client
  deploy:
   replicas: 0
  depends_on:
   - mongodb
   - postgres
  volumes:
  - $DIR:/dir
  environment:
   - DB_URI=$DB_URI
   - BENCH_DOCS=$BENCH_DOCS
   - BENCH_NUM=$BENCH_NUM
   - BENCH_BYTES=$BENCH_BYTES
  command: -f /dir/lib.js

 # MongoDB 

 mongodb:
  image: docker.io/mongodb/mongodb-community-server:latest
  deploy:
   replicas: 1
 
 # PostgreSQL

 postgres:
  image: postgres
  command: postgres -c shared_buffers=384MB
  environment:
   - POSTGRES_PASSWORD=xxx
  volumes :
   - ./bench1/init.sql:/docker-entrypoint-initdb.d/init.sql
  deploy:
   replicas: 1


# https://last9.io/blog/docker-monitoring-with-prometheus-a-step-by-step-guide/

 prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

 cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

 node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

 grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    user: "0:0"
    volumes:
      - ./grafana:/etc/grafana:ro
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
